<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="..\buildMultiTargeting\Crumpled.RobotsTxt.props" />
	<ItemGroup>
		<UmbracoJsonSchemaFiles Include="$(MSBuildThisFileDirectory)..\appsettings-schema.Crumpled.RobotsTxt.json" Weight="-50" />
	</ItemGroup>
</Project>